/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAoVivoRouteImport } from './routes/_authenticated/ao-vivo'
import { Route as AuthenticatedCadastrosRouteImport } from './routes/_authenticated/cadastros'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedImprimirIdRouteImport } from './routes/_authenticated/imprimir/$id'
import { Route as AuthenticatedOsIndexRouteImport } from './routes/_authenticated/os/index'
import { Route as AuthenticatedOsIdRouteImport } from './routes/_authenticated/os/$id'
import { Route as AuthenticatedOsNovaRouteImport } from './routes/_authenticated/os/nova'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAoVivoRoute = AuthenticatedAoVivoRouteImport.update({
  id: '/ao-vivo',
  path: '/ao-vivo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadastrosRoute = AuthenticatedCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImprimirIdRoute = AuthenticatedImprimirIdRouteImport.update({
  id: '/imprimir/$id',
  path: '/imprimir/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOsIndexRoute = AuthenticatedOsIndexRouteImport.update({
  id: '/os/',
  path: '/os/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOsIdRoute = AuthenticatedOsIdRouteImport.update({
  id: '/os/$id',
  path: '/os/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOsNovaRoute = AuthenticatedOsNovaRouteImport.update({
  id: '/os/nova',
  path: '/os/nova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ao-vivo': typeof AuthenticatedAoVivoRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/imprimir/$id': typeof AuthenticatedImprimirIdRoute
  '/os/$id': typeof AuthenticatedOsIdRoute
  '/os/nova': typeof AuthenticatedOsNovaRoute
  '/os/': typeof AuthenticatedOsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ao-vivo': typeof AuthenticatedAoVivoRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/imprimir/$id': typeof AuthenticatedImprimirIdRoute
  '/os/$id': typeof AuthenticatedOsIdRoute
  '/os/nova': typeof AuthenticatedOsNovaRoute
  '/os': typeof AuthenticatedOsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/ao-vivo': typeof AuthenticatedAoVivoRoute
  '/_authenticated/cadastros': typeof AuthenticatedCadastrosRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/imprimir/$id': typeof AuthenticatedImprimirIdRoute
  '/_authenticated/os/$id': typeof AuthenticatedOsIdRoute
  '/_authenticated/os/nova': typeof AuthenticatedOsNovaRoute
  '/_authenticated/os/': typeof AuthenticatedOsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ao-vivo'
    | '/cadastros'
    | '/financeiro'
    | '/painel'
    | '/usuarios'
    | '/imprimir/$id'
    | '/os/$id'
    | '/os/nova'
    | '/os/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ao-vivo'
    | '/cadastros'
    | '/financeiro'
    | '/painel'
    | '/usuarios'
    | '/imprimir/$id'
    | '/os/$id'
    | '/os/nova'
    | '/os'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/ao-vivo'
    | '/_authenticated/cadastros'
    | '/_authenticated/financeiro'
    | '/_authenticated/painel'
    | '/_authenticated/usuarios'
    | '/_authenticated/imprimir/$id'
    | '/_authenticated/os/$id'
    | '/_authenticated/os/nova'
    | '/_authenticated/os/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ao-vivo': {
      id: '/_authenticated/ao-vivo'
      path: '/ao-vivo'
      fullPath: '/ao-vivo'
      preLoaderRoute: typeof AuthenticatedAoVivoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros': {
      id: '/_authenticated/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AuthenticatedCadastrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/imprimir/$id': {
      id: '/_authenticated/imprimir/$id'
      path: '/imprimir/$id'
      fullPath: '/imprimir/$id'
      preLoaderRoute: typeof AuthenticatedImprimirIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/os/': {
      id: '/_authenticated/os/'
      path: '/os'
      fullPath: '/os/'
      preLoaderRoute: typeof AuthenticatedOsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/os/$id': {
      id: '/_authenticated/os/$id'
      path: '/os/$id'
      fullPath: '/os/$id'
      preLoaderRoute: typeof AuthenticatedOsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/os/nova': {
      id: '/_authenticated/os/nova'
      path: '/os/nova'
      fullPath: '/os/nova'
      preLoaderRoute: typeof AuthenticatedOsNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAoVivoRoute: typeof AuthenticatedAoVivoRoute
  AuthenticatedCadastrosRoute: typeof AuthenticatedCadastrosRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedImprimirIdRoute: typeof AuthenticatedImprimirIdRoute
  AuthenticatedOsIdRoute: typeof AuthenticatedOsIdRoute
  AuthenticatedOsNovaRoute: typeof AuthenticatedOsNovaRoute
  AuthenticatedOsIndexRoute: typeof AuthenticatedOsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAoVivoRoute: AuthenticatedAoVivoRoute,
  AuthenticatedCadastrosRoute: AuthenticatedCadastrosRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedImprimirIdRoute: AuthenticatedImprimirIdRoute,
  AuthenticatedOsIdRoute: AuthenticatedOsIdRoute,
  AuthenticatedOsNovaRoute: AuthenticatedOsNovaRoute,
  AuthenticatedOsIndexRoute: AuthenticatedOsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
